# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 676f925a37d27c1a5d13a033679f73a992f1626519776602780c80b94b623e1704b21e56eb8d70bf27de21da293b5e5a1c53600dcabed636a06fa3b3cfdc93b7

test:
  secret_key_base: 3a8630c7015747eed914348d5e1836d7bdcbdd21c18f24ddf0207bf16007bae24370121d0b8c545e789b2bc4ed5e5437350e4f5e5cb7463b87aa5c39e507d270

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
